### ISSUE TITLE
Exception when loading module

### ISSUE THREAD

**Issue by boostpaal** [rse/syntax#3]
When requiring the module, I get:
```
TypeError: Cannot read property 'match' of undefined
    at Syntax.config (/mnt/c/Users/pth/code/bubls/node_modules/syntax/lib/syntax.node.js:1504:54)
    at new Syntax (/mnt/c/Users/pth/code/bubls/node_modules/syntax/lib/syntax.node.js:1455:16)
    at Node.xmlTag.children.each (/mnt/c/Users/pth/code/bubls/server/utils.js:133:18)
    at initialize.exports.each (/mnt/c/Users/pth/code/bubls/node_modules/cheerio/lib/api/traversing.js:300:24)
    at Object.markdownToHtml (/mnt/c/Users/pth/code/bubls/server/utils.js:117:21)
    at Object.defaults (/mnt/c/Users/pth/code/bubls/server/init.js:56:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Seems related to highlight.js, but I can't see where.

Running on node.js v.10.12.0

**Comment by boostpaal** [comment]
Closing this as no response.
